### ISSUE TITLE
Fix link to S2S page

### ISSUE THREAD

**Issue by elliotwhitehead** [casassg/events-landing#13]
We don't have an SSL cert on S2S.org, so any links to that page should point to `http://`, not `https://`

**Comment by casassg** [comment]
This is weird, its linked to the http page: https://github.com/HackCU/events/blob/771c4225db8b7a18cd9deadf3dd5263c741a2e17/_data/footer_links.yml#L4

**Comment by elliotwhitehead** [comment]
Oh... What the heck.

**Comment by elliotwhitehead** [comment]
@casassg Found the culprit 🔍 

https://github.com/HackCU/events/blob/master/_data/events.yml#L8

**Comment by casassg** [comment]
True, I didn't notice this one! Good catch!

**Comment by elliotwhitehead** [comment]
How did you embed line 4 up there? I figured pasting the link would do it automatically 😛

**Comment by casassg** [comment]
Idk, I pasted the permalink -.- I didn't do anything XD

**Comment by elliotwhitehead** [comment]
https://github.com/HackCU/events/blame/062394cf972c499b7e5555adce3bb4c2a1892929/_data/events.yml#L8
